version: "3.7"

services:
  bd:
    image: postgres:11.5
    ports:
      - 5432:5432
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=pulini_supermercado_db